[project]
name = "diabetes-detection"
version = "0.1.0"
description = "this is my first machine learning project using sklearn and fastapi"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "fastapi>=0.128.0",
    "numpy>=2.4.1",
    "uvicorn>=0.40.0",
]
